const products = [
    {
      id: 1,
      title: 'Burberry Brit 100ml EDP',
      price: 6000,
      img: './images/p1.jpg',
      desc: `Burberry Brit je cvetni voćni miris za žene. Predstavljen je 2003. godine. Parfem je kreirala Natalie Gracia-Cetto.`,
      inList: 0,
    },
    {
      id: 2,
      title: 'Christina Aguilera 50ml EDP',
      price: 3000 ,
      img: './images/p2.jpg',
      desc: `Christina Aguilera je orijentalni cvetni miris za žene. Parfem je predstavljen 2007. godine.`,
      inList: 0,
    },
    {
      id: 3,
      title: 'Naomi Campbell 50ml EDT',
      price: 3000,
      img: './images/p3.jpg',
      desc: `Naomi Campbell je cvetni miris za žene. Parfem je napravljen 1999. godine, a kreirala ga je Ursula Wandel.`,
      inList: 0,
    },
    {
      id: 4,
      title: 'Elizabeth Arden Green Tea 100ml EDP',
      price: 3000,
      img: './images/p4.jpg',
      desc: `Elizabeth Arden Green Tea je citrusni aromatični miris za žene. Green Tea je predstavljen 1999. godine. Parfem je kreirao Francis Kurkdjian.`,
      inList: 0,
    },
    {
      id: 5,
      title: 'Jennifer Lopez Still 100ml EDP',
      price: 3600,
      img: './images/p5.jpg',
      desc: `Jennifer Lopez Still je cvetni miris za žene. Still je predstavljen 2003. godine, kreirao ga je Michel Girard.`,
      inList: 0,
    },
    {
      id: 6,
      title: 'Calvin Klein Truth 100ml EDP',
      price: 4200,
      img: './images/p6.jpg',
      desc: `Calvin Klein Truth je orijentalni drveni miris za žene. Truth je predstavljen 2000. godine. Kreirali su ga Alberto Morillas, Jacques Cavallier i Thierry Wasser. `,
      inList: 0,
    },
    {
      id: 7,
      title: 'Salvador Dali Laguna 100ml EDT',
      price: 4200,
      img: './images/p7.jpg',
      desc: `Salvador Dali Laguna je cvetni voćni miris za žene. Laguna je predstavljen 1991. godine. Parfem je kreirao Mark Buxton. `,
      inList: 0,
    },
    {
      id: 8,
      title: 'Hugo Boss Jour Pour Femme 75ml EDP',
      price: 4800,
      img: './images/p8.jpg',
      desc: `Hugo Boss Jour Pour Femme je cvetni miris za žene. Boss Jour Pour Femme je predstavljen 2013. godine.`,
      inList: 0,
    },
    {
      id: 9,
      title: 'Jil Sander Everose 75ml EDT',
      price: 4800,
      img: './images/p9.jpg',
      desc: `Jil Sander Everose je kiparisni cvetni miris za žene. Everose je predstavljen 2012. godine.`,
      inList: 0,
    },
    {
      id: 10,
      title: 'John Richmond 100ml EDP',
      price: 4800,
      img: './images/p10.jpg',
      desc: `John Richmond je cvetni voćni miris za žene. Na tržištu se pojavio 2009. godine.`,
      inList: 0,
    },
    {
      id: 11,
      title: 'Karl Lagerfeld For Her 85ml EDP',
      price: 4800 ,
      img: './images/p11.jpg',
      desc: `Karl Lagerfeld For Her je cvetni voćni miris za žene. Predstavljen je 2014. godine, a kreirali su ga Serge Majoullier i Christine Nagel.`,
      inList: 0,
    },
    {
      id: 12,
      title: 'Hugo Boss Nuit Pour Femme 75ml EDP',
      price: 5400,
      img: './images/p12.jpg',
      desc: `Hugo Boss Nuit Pour Femme je cvetni miris za žene. Parfem je predstavljen 2012. godine`,
      inList: 0,
    },
    {
      id: 13,
      title: 'Cerruti 1881 100ml EDT',
      price: 5400,
      img: './images/p13.jpg',
      desc: `Cerruti 1881 je cvetni miris za žene. Parfem je predstavljen 1995. godine, a kreirala ga je Claire Cain.`,
      inList: 0,
    },
    {
      id: 14,
      title: 'Burberry Women 100ml EDP',
      price: 5400,
      img: './images/p14.jpg',
      desc: `Burberry Women je cvetni voćni miris za žene. Parfem je predstavljen 1995. godine, a njegov tvorac je Michel Almairac.`,
      inList: 0,
    },
    {
      id: 15,
      title: 'Armaf Club de Nuit Women 105ml EDP',
      category: 'nega kose',
      price: 5400,
      img: './images/p15.jpg',
      desc: `Armaf Club de Nuit Women je cvetni voćni miris za žene. Na tržištu se pojavio 2016. godine. Gotovo da je identičan parfemu Chanel Coco Mademoiselle.`,
      inList: 0,
    },
    {
      id: 16,
      title: 'Cacharel Anais Anais 100ml EDT',
      price: 6000,
      img: './images/p16.jpg',
      desc: `Cacharel Anais Anais je elegantan, ženstven i senzualan miris namenjen prefinjenim ženama. Ova predivna cvetna kompozicija odiše aromama zumbula, cveta pomorandže, ruže, jasmina, ćilibara, tamjana i sandalovine`,
      inList: 0,
    },
    {
      id: 17,
      title: 'Versace Vanitas 100ml EDP',
      price: 6000,
      img: './images/p17.jpg',
      desc: `Versace Vanitas je cvetni miris za žene. Vanitas je predstavljen 2011. godine. Parfem je kreirala Dora Baghriche. `,
      inList: 0,
    },
    {
      id: 18,
      title: 'Montblanc Signature 90ml EDP',
      price: 6600,
      img: './images/p18.jpg',
      desc: `Montblanc Signature je orijentalno-cvetni i mošusni miris namenjen ženama. Kompoziciju su kreirali parfimeri Guillaume Flavigny i Natalie Gracia-Cetto sa ciljem da naprave transparentan, svetlucav, elegantan i čist miris koji poseduje i senzualnu stranu zahvaljujući vanili i ambernom karakteru benzoina.`,
      inList: 0,
    },
  ];
  export default products;